version: '3.9'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro
      - /pds/caddy/data:/pds/caddy/data
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - pds
    restart: unless-stopped

  pds:
    container_name: pds
    image: ghcr.io/bluesky-social/pds:0.4
    expose:
      - "3000"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /pds
        target: /pds
    env_file:
      - /pds/pds.env

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: "@midnight"
