name: Build and Update Public Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-update-public:
    runs-on: ubuntu-latest
    env:
      HUGO_BASEURL: https://btuckerc.com
      HUGO_ENV: production
      HUGO_ENABLEGITINFO: true
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          echo "Building with base URL: $HUGO_BASEURL"
          hugo -t paper --minify --baseURL "$HUGO_BASEURL" --gc --cleanDestinationDir --environment production

      - name: Update public branch
        run: |
          # Configure Git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Create/switch to public branch
          git checkout public 2>/dev/null || git checkout -b public

          # Clear existing contents
          git rm -rf .

          # Copy contents from main branch's public directory
          git checkout main -- public/

          ./scripts/migrate_attachments.sh

          # Move contents to root
          mv public/* .
          rm -rf public/

          # Commit and push
          git add .
          git commit -m "Update public branch from main branch public directory" || echo "No changes to commit"
          git push origin public -f
