name: Update Public Branch

on:
  push:
    branches:
      - main

jobs:
  update-public-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create/Update public branch
        run: |
          # Create public branch if it doesn't exist, or switch to it if it does
          git checkout public 2>/dev/null || git checkout -b public

          # Remove all files from public branch
          git rm -rf .

          # Copy contents from main branch's public directory
          git checkout main -- public/

          # Move contents of public directory to root
          mv public/* .
          rm -rf public/

          # Stage all changes
          git add .

          # Configure Git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Commit and push changes
          git commit -m "Update public branch from main branch public directory" || echo "No changes to commit"
          git push origin public -f
